// Get litters
### 
GET http://localhost:8080/litters

// Get specific litter
###
GET http://localhost:8080/litters/646508676d2238deabe1bc04

// Create new litter
###
POST http://localhost:8080/litters HTTP/1.1
Content-Type: application/json

{
    "litterAKC": "AKC Registration",
    "sireName": "Jacob",
    "damName": "Oakley",
    "litterConceived": "2023-05-14",
    "litterDelivered": "2023-07-09",
    "femalesBorn": 5,
    "femalesSurvived": 5,
    "malesBorn": 5,
    "malesSurvived": 5,
    "puppiesYellow": 3,
    "puppiesChocolate": 3,
    "puppiesBlack": 4
}

// Update litter
###
PUT http://localhost:8080/litters/646d004e62c7857fd0810a4c HTTP/1.1
Content-Type: application/json

{
    "litterAKC": "AKC Registration",
    "sireName": "Jacob",
    "damName": "Hazel",
    "litterConceived": "2023-05-14",
    "litterDelivered": "2023-07-09",
    "femalesBorn": 5,
    "femalesSurvived": 5,
    "malesBorn": 5,
    "malesSurvived": 5,
    "puppiesYellow": 3,
    "puppiesChocolate": 3,
    "puppiesBlack": 4
}

// Delete contact
###
DELETE http://localhost:8080/litters/646d004e62c7857fd0810a4c


// Render
// Get litters
### 
GET https://puppies-api-ek0y.onrender.com/litters

// Get specific litter
###
GET https://puppies-api-ek0y.onrender.com/litters/644b153f6adc3b1dfb8c9b2f

// Create new litter
###
POST https://puppies-api-ek0y.onrender.com/litters HTTP/1.1
Content-Type: application/json

{
    "litterAKC": "Test AKC Registration",
    "sireName": "Jacob",
    "damName": "Oakley",
    "litterConceived": "2023-05-14",
    "litterDelivered": "2023-07-09",
    "femalesBorn": 5,
    "femalesSurvived": 5,
    "malesBorn": 5,
    "malesSurvived": 5,
    "puppiesYellow": 3,
    "puppiesChocolate": 3,
    "puppiesBlack": 4,
    "litterNote": "Healthy litter."
}

// Update litter
###
PUT https://puppies-api-ek0y.onrender.com/litters/6455667dba6f64df53b8efe5 HTTP/1.1
Content-Type: application/json

{
    "litterAKC": "Test AKC Registration",
    "sireName": "Jacob",
    "damName": "Oakley",
    "litterConceived": "2023-05-14",
    "litterDelivered": "2023-07-09",
    "femalesBorn": 5,
    "femalesSurvived": 5,
    "malesBorn": 5,
    "malesSurvived": 5,
    "puppiesYellow": 3,
    "puppiesChocolate": 3,
    "puppiesBlack": 4
}

// Delete contact
###
DELETE https://puppies-api-ek0y.onrender.com/litters/645e6630cb12621bc1e384c3
