// Get puppies
### 
GET http://localhost:8080/puppies

// Get specific puppy
###
GET http://localhost:8080/puppies/646503dd6d2238deabe1bbf9

// Create new puppy
###
POST http://localhost:8080/puppies HTTP/1.1
Content-Type: application/json

{
    "puppyTempName": "$New Puppy Test",
    "puppyDOB": "2023-05-20",
    "puppySex": "M",
    "puppyColor": "chocolate",
    "puppyCollar": "orange",
    "puppyAKC": "Resigtration #",
    "puppyNewName": "My New Name"
}

// Update puppy
###
PUT http://localhost:8080/puppies/646ce02a5376a53e6de09a29 HTTP/1.1
Content-Type: application/json

{
    "puppyTempName": "New Puppy Test",
    "puppyDOB": "2023-05-20",
    "puppySex": "M",
    "puppyColor": "chocolate",
    "puppyCollar": "orange",
    "puppyAKC": "AKC #",
    "puppyNewName": "My New Name"
}

// Delete puppy
###
DELETE http://localhost:8080/puppies/646f453d2c2b774ed28d6062


// Render
// Get puppies
### 
GET https://puppies-api-ek0y.onrender.com/puppies

// Get specific puppy
###
GET https://puppies-api-ek0y.onrender.com/puppies/646cf4789d5927e53ed0b1ed

// Create new puppy
###
POST https://puppies-api-ek0y.onrender.com/puppies HTTP/1.1
Content-Type: application/json

{
    "puppyTempName": "Puppy Test",
    "puppyDOB": "2023-05-20",
    "puppySex": "M",
    "puppyColor": "chocolate",
    "puppyCollar": "orange",
    "puppyAKC": "SS1234",
    "puppyNewName": "My New Name"
}

// Update puppy
###
PUThttps://puppies-api-ek0y.onrender.com/puppies/6455667dba6f64df53b8efe5 HTTP/1.1
Content-Type: application/json

{
    "puppyTempName": "New Puppy Test",
    "puppyDOB": "2023-05-20",
    "puppySex": "M",
    "puppyColor": "chocolate",
    "puppyCollar": "orange",
    "puppyAKC": "orange",
    "puppyNewName": "My New Name"
}

// Delete puppy
###
DELETE https://puppies-api-ek0y.onrender.com/puppies/646f447fe225c3063bb6cae1
